config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/lost_pets", to: "lost_pets#index"

  # get "/lost_pets/new", to: "lost_pets#new", as: :lost_pet_new
  
  # get "/lost_pets/:id", to: "lost_pets#show", as: :lost_pet

  # post "/lost_pets", to: "lost_pets#create"

  # get "/lost_pets/:id/edit", to: "lost_pets#edit"

  # patch "/lost_pets/:id/", to: "lost_pets#update" 

  # delete "/lost_pets/:id", to: "lost_pets#destroy"

  resources :lost_pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lost_pet.rb
class LostPet < ApplicationRecord

    validates :name, presence: true
    validates :species, inclusion: { in: %w(dog cat rabbit snake turtle) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lost_pets_controller.rb
class LostPetsController < ApplicationController

    before_action :set_lost_pet, only: [:show, :edit, :update, :destroy]

    def index

        @lost_pets = LostPet.all
    end

    def show
        
    end

    def new
        @lost_pet = LostPet.new()        
    end

    def create
        @lost_pet = LostPet.new(pets_params)
        
        if @lost_pet.save
            redirect_to lost_pets_path
        else 
            render :new
        end   

    end

    
    def edit
                
    end

    def update
        
        if @lost_pet.update(pets_params)
            redirect_to lost_pets_path
        else 
            render :edit
        end   

    end

    def destroy
        
        @lost_pet.destroy
        
        redirect_to lost_pets_path
    end

    private

    def pets_params
        params.require(:lost_pet).permit(:name, :address, :found_on, :species)
    end

    def set_lost_pet
        @lost_pet = LostPet.find(params[:id])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lost_pets_helper.rb
module LostPetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lost_pets/edit.html.erb
<%#= form_for(@lost_pet) do |f| %>
   <%#= f.text_field :name %>
   <%#= f.text_field :address %>
   <%#= f.text_field :species %>
   <%#= f.date_field :found_on, class: "date-field" %>
   <%#= f.submit %>
<%# end %>


<%= simple_form_for(@lost_pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/lost_pets/index.html.erb
<h2>index page</h2>

<% @lost_pets.each do |pet| %>
    <div><%= pet.name %></div>
    <div><%= pet.found_on %></div>
    <%= link_to "Show Pet", lost_pet_path(pet) %>
    <%= link_to "Delete Pet", lost_pet_path(pet), method: :delete, data: {confirm: "Are you sure?"} %>
    <br>
    <br>
    <br>
<% end %>

app/views/lost_pets/new.html.erb
<%#= form_for(@lost_pet) do |f| %>
   <%#= f.text_field :name %>
   <%#= f.text_field :address %>
   <%#= f.text_field :species %>
   <%#= f.date_field :found_on, class: "date-field" %>
   <%#= f.submit %>
<%# end %>

<div class="m-auto w-50 p-5 bg bg-primary">
    <%= simple_form_for(@lost_pet) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :species %>
        <%= f.input :found_on %>
        <%= f.submit %>
    <% end %>
</div>

app/views/lost_pets/show.html.erb
<h1><%= @lost_pet.name %></h1>
<h1><%= @lost_pet.address %></h1>
<h1><%= @lost_pet.found_on %></h1>
<h1><%= @lost_pet.species %></h1>